config/routes.rb
Theibarb::Application.routes.draw do
  get "backend/index"
  get "backend/show"
  get "backend/new"
  get "backend/edit"
  get "backend/update"
  get "backend/create"
  get "backend/destroy"
  resources :nodes

  resources :users

end

app/models/node.rb
class Node < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :uid, :name, :password, :mail, :tagline, :last_update, :last_access, :status, :timezone, :metadata, :user_roles
  
  %w[provider provider_uid provider_secret].each do |key|
    attr_accessible key
    scope "has_#{key}", lambda { |value| where("metadata @> (? => ?)", key, value) }
    
    define_method(key) do
      metadata && metadata[key]
    end
  
    define_method("#{key}=") do |value|
      self.metadata = (metadata || {}).merge(key => value)
    end
  end  

end


      

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def update
  end

  def create
  end

  def destroy
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def upsert
    @node = Post.new(node_params[:post])  
  
    respond_to do |format|  
      if @node.save  
        format.html { redirect_to(@node, :notice => 'Status updated.') }  
        format.js  
      else  
        format.html { render :action => "new" }  
        format.js  
      end  
    end  
  end
  
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render action: 'show', status: :created, location: @node }
      else
        format.html { render action: 'new' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.js   { render :nothing => true }  
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:node_id, :version_id, :current_version_id, :language, :title, :authors_id, :status, :created_at, :updated_at, :unpublished_at, :first_published, :last_published, :rank, :metadata, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:uid, :name, :password, :mail, :tagline, :last_update, :last_access, :status, :timezone, :metadata, :user_roles)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend_helper.rb
module BackendHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/backend/create.html.erb
<h1>Backend#create</h1>
<p>Find me in app/views/backend/create.html.erb</p>

app/views/backend/destroy.html.erb
<h1>Backend#destroy</h1>
<p>Find me in app/views/backend/destroy.html.erb</p>

app/views/backend/edit.html.erb
<h1>Backend#edit</h1>
<p>Find me in app/views/backend/edit.html.erb</p>

app/views/backend/index.html.erb
<h1>Backend#index</h1>
<p>Find me in app/views/backend/index.html.erb</p>


<h1>Routes</h1>
<h1>Content</h1>
<h1>Users</h1>

app/views/backend/new.html.erb
<h1>Backend#new</h1>
<p>Find me in app/views/backend/new.html.erb</p>

app/views/backend/show.html.erb
<h1>Backend#show</h1>
<p>Find me in app/views/backend/show.html.erb</p>

app/views/backend/update.html.erb
<h1>Backend#update</h1>
<p>Find me in app/views/backend/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Theibarb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<input id="user_born_on" name="user[born_on]" type="datetime" />
  <div class="field">
    <%= f.label :node_id %><br />
    <%= f.number_field :node_id %>
  </div>
  <div class="field">
    <%= f.label :version_id %><br />
    <%= f.number_field :version_id %>
  </div>
  <div class="field">
    <%= f.label :current_version_id %><br />
    <%= f.number_field :current_version_id %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :authors_id %><br />
    <%= f.text_field :authors_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :unpublished_at %><br />
    <%= f.datetime_local_field :unpublished_at %>
  </div>
  <div class="field">
    <%= f.label :first_published %><br />
    <%= f.datetime_select :first_published %>
  </div>
  <div class="field">
    <%= f.label :last_published %><br />
    <%= f.datetime_select :last_published %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.text_field :rank %>
  </div>
  <div class="field">
    <%= f.label :metadata %><br />
    <%= f.text_field :metadata %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <thead>
    <tr>
      <th>Node</th>
      <th>Version</th>
      <th>Current version</th>
      <th>Language</th>
      <th>Title</th>
      <th>Authors</th>
      <th>Status</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Unpublished at</th>
      <th>First published</th>
      <th>Last published</th>
      <th>Rank</th>
      <th>Metadata</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
    <tr>
      <td><%= node.node_id %></td>
      <td><%= node.version_id %></td>
      <td><%= node.current_version_id %></td>
      <td><%= node.language %></td>
      <td><%= node.title %></td>
      <td><%= node.authors_id %></td>
      <td><%= node.status %></td>
      <td><%= node.created_at %></td>
      <td><%= node.updated_at %></td>
      <td><%= node.unpublished_at %></td>
      <td><%= node.first_published %></td>
      <td><%= node.last_published %></td>
      <td><%= node.rank %></td>
      <td><%= node.metadata %></td>
      <td><%= node.content %></td>
      <td><%= link_to 'Show', node %></td>
      <td><%= link_to 'Edit', edit_node_path(node) %></td>
      <td><%= link_to 'Destroy', node, :confirm => 'Are you sure?', :method => :delete, :remote=>true, :class=>'delete_post' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Node:</strong>
  <%= @node.node_id %>
</p>

<p>
  <strong>Version:</strong>
  <%= @node.version_id %>
</p>

<p>
  <strong>Current version:</strong>
  <%= @node.current_version_id %>
</p>

<p>
  <strong>Language:</strong>
  <%= @node.language %>
</p>

<p>
  <strong>Title:</strong>
  <%= @node.title %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @node.authors_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @node.status %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @node.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @node.updated_at %>
</p>

<p>
  <strong>Unpublished at:</strong>
  <%= @node.unpublished_at %>
</p>

<p>
  <strong>First published:</strong>
  <%= @node.first_published %>
</p>

<p>
  <strong>Last published:</strong>
  <%= @node.last_published %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @node.rank %>
</p>

<p>
  <strong>Metadata:</strong>
  <%= @node.metadata %>
</p>

<p>
  <strong>Content:</strong>
  <%= @node.content %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :id => 'userform' }) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :uid, :class => 'label'%><%= f.text_field :uid %>
    </div>
    <div class="field">
      <%= f.label :name, :class => 'label' %><%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :password, :class => 'label' %><%= f.text_field :password %>
    </div>
    <div class="field">
      <%= f.label :mail, :class => 'label' %><%= f.text_field :mail %>
    </div>
    <div class="field">
      <%= f.label :tagline, :class => 'label' %><%= f.text_field :tagline %>
    </div>
    <div class="field">
      <%= f.label :last_update, :class => 'label' %><%= f.text_field :last_update %>
    </div>
    <div class="field">
      <%= f.label :last_access, :class => 'label' %><%= f.text_field :last_access %>
    </div>
    <div class="field">
      <%= f.label :status, :class => 'label' %><%= f.text_field :status %>
    </div>
    <div class="field">
      <%= f.label :timezone, :class => 'label' %><%= f.text_field :timezone %>
    </div>
    <div class="field">
      <%= f.label :metadata, :class => 'label' %><%= f.text_field :metadata %>
    </div>
    <div class="field">
      <%= f.label :user_roles, :class => 'label' %><%= f.text_field :user_roles %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Name</th>
      <th>Password</th>
      <th>Mail</th>
      <th>Tagline</th>
      <th>Last update</th>
      <th>Last access</th>
      <th>Status</th>
      <th>Timezone</th>
      <th>Metadata</th>
      <th>User roles</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.uid %></td>
      <td><%= user.name %></td>
      <td><%= user.password %></td>
      <td><%= user.mail %></td>
      <td><%= user.tagline %></td>
      <td><%= user.last_update %></td>
      <td><%= user.last_access %></td>
      <td><%= user.status %></td>
      <td><%= user.timezone %></td>
      <td><%= user.metadata %></td>
      <td><%= user.user_roles %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @user.mail %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @user.tagline %>
</p>

<p>
  <strong>Last update:</strong>
  <%= @user.last_update %>
</p>

<p>
  <strong>Last access:</strong>
  <%= @user.last_access %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<p>
  <strong>Timezone:</strong>
  <%= @user.timezone %>
</p>

<p>
  <strong>Metadata:</strong>
  <%= @user.metadata %>
</p>

<p>
  <strong>User roles:</strong>
  <%= @user.user_roles %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>